### ISSUE TITLE
ZoneId parsing error messages differ from those of java.time

### ISSUE THREAD

**Issue by travisbrown** [cquiroz/scala-java-time#132]
For example, on the JVM:

```scala
scala> java.time.ZoneId.of("X")
java.time.DateTimeException: Invalid ID for ZoneOffset, invalid format: X
  at java.base/java.time.ZoneOffset.of(ZoneOffset.java:241)
  at java.base/java.time.ZoneId.of(ZoneId.java:402)
  at java.base/java.time.ZoneId.of(ZoneId.java:356)
  ... 36 elided
```
While with scala-java-time on Scala.js the message is `Invalid zone: X`.

**Comment by cquiroz** [comment]
Thanks for the report, we've tried to match and do test for these cases but obviously we missed this one
