### ISSUE TITLE
Linking issue with scala-java-time-tzdb 2.0.0-RC4_2019c on scala.js 0.6.32

### ISSUE THREAD

**Issue by ngbinh** [cquiroz/scala-java-time#168]
Hi,

I tried to update scala-java-time-tzdb to the latest version and get this linking error on scala.js 0.6.32.

```
org.scalajs.core.ir.IRVersionNotSupportedException: Failed to deserialize info of file compiled with Scala.js 1.0 (supported: 0.6.0, 0.6.13, 0.6.3, 0.6.17, 0.6.4, 0.6.6, 0.6.14,
 0.6.8, 0.6.30, 0.6.29, 0.6.5, 0.6.15):/path-to-maven-cache/io/github/cquiroz/scala-java-time-tzdb_sjs0.6_2.12/2.0
.0-RC4_2019c/scala-java-time-tzdb_sjs0.6_2.12-2.0.0-RC4_2019c.jar:zonedb/java/tzdb$ameor.sjsir
[error]         at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile.info(VirtualFiles.scala:165)
[error]         at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile.info$(VirtualFiles.scala:156)
[error]         at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.info(MemFiles.scala:107)
[error]         at org.scalajs.core.tools.io.IRFileCache$PersistentIRFile.<init>(IRFileCache.scala:247)
[error]         at org.scalajs.core.tools.io.IRFileCache$PersistedFiles.$anonfun$update$5(IRFileCache.scala:222)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:231)

```

**Comment by cquiroz** [comment]
RC4 got botched due to some release issue. Can you try RC5?

**Comment by ngbinh** [comment]
I don't see RC5 in maven https://mvnrepository.com/artifact/io.github.cquiroz/scala-java-time-tzdb_sjs0.6_2.12

**Comment by cquiroz** [comment]
I see somehow RC5 didn't include tzdb. In the meantime could you use `sbt-tzdb`?

**Comment by ngbinh** [comment]
I can try that out

**Comment by cquiroz** [comment]
Did this work for you? Can we close this issue?

**Comment by ngbinh** [comment]
yes, `sbt-tzdb` works for me. But I believe, for other users convinience, an working version should be published.
