### ISSUE TITLE
ZoneOffset.of("Z") behaviour differs from JVM 

### ISSUE THREAD

**Issue by keynmol** [cquiroz/scala-java-time#518]
Scala CLI reproducer ("Invalid ID for ZoneOffset, invalid format: Z"):

```
$ scala-cli -e 'java.time.ZoneOffset.of("Z")' --js --dep io.github.cquiroz::scala-java-time::2.6.0
Downloading 4 dependencies
Compiling project (Scala 3.5.0, Scala.js 1.16.0)
Compiled project (Scala 3.5.0, Scala.js 1.16.0)
/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/main13411997713378497798.js:1213
      throw new $c_Ljava_time_DateTimeException(("Invalid ID for ZoneOffset, invalid format: " + _offsetId));
      ^

java.time.DateTimeException: Invalid ID for ZoneOffset, invalid format: Z
    at $c_Ljava_time_ZoneOffset$.of__T__Ljava_time_ZoneOffset (/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/main13411997713378497798.js:1213:13)
    at new $c_Lsnippet$ (/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/main13411997713378497798.js:2166:31)
    at $m_Lsnippet$ (/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/main13411997713378497798.js:2180:20)
    at $c_Lsnippet＿sc$.main__AT__V (/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/main13411997713378497798.js:2200:16)
    at $s_Lsnippet＿sc__main__AT__V (/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/main13411997713378497798.js:2185:26)
    at Object.<anonymous> (/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/main13411997713378497798.js:3970:1)
    at Object.<anonymous> (/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/main13411997713378497798.js:3971:4)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32) {
  jl_Throwable__f_s: 'Invalid ID for ZoneOffset, invalid format: Z'
}
```

On JVM `scala-cli -e 'java.time.ZoneOffset.of("Z")` succeeds just fine.

I tried adding `--dep io.github.cquiroz::scala-java-time-tzdb:2.6.0` but result is the same (shouldn't matter anyways, given docs state that "By default UTC will always be available but otherwise the library will work fine and produce the smallest possible js file")

**Comment by cquiroz** [comment]
What is the Z timezone?, Is it the same as `UTC`?

**Comment by keynmol** [comment]
Yep, that's the id of UTC: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/ZoneOffset.html#UTC

**Comment by cquiroz** [comment]
ok, thanks. I think we can accomplish this adding an alias for UTC

**Comment by cquiroz** [comment]
sure, I'll be happy to accept a PR
